services:
  connect-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=purlo
      - POSTGRES_PASSWORD=purlo
      - POSTGRES_DB=purlo

  jaeger:
    image: jaegertracing/jaeger:2.8.0
    ports:
      - "16686:16686" # UI
      - "14268:14268" # Traces HTTP
      - "4318:4318" # OTLP/HTTP